<div style="background-color: #4b3832; padding: 20px; border-radius: 10px; box-shadow: 5px 5px 10px #888888;">
  <h1 style="color: white; font-size: 30px; font-weight: bold; text-align: center; text-shadow: 2px 2px 4px #000000;">import the needed libraries😉</h1>
</div>

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import plotly.express as px
import matplotlib.pyplot as plt
import plotly.graph_objects as go
from plotly.offline import iplot, plot
from plotly.subplots import make_subplots

colors = ["#b1e7cd","#854442","#000000","#fff4e6","#3c2f2f",
           "#be9b7b ","#512E5F","#45B39D","#AAB7B8 ","#20B2AA",
           "#FF69B4","#00CED1","#FF7F50","#7FFF00","#DA70D6"]

<div style="background-color: #4b3832; padding: 20px; border-radius: 10px; box-shadow: 5px 5px 10px #888888;">
  <h1 style="color: white; font-size: 30px; font-weight: bold; text-align: center; text-shadow: 2px 2px 4px #000000;">first we load the data and get some info✌️</h1>
</div>

In [2]:
car = pd.read_csv("/kaggle/input/cars-dataset/cars.csv")

In [3]:
#LETS GET SAMPLE FROM THE DATA
car.sample(5)

,First Name,Last Name,Country,Car Brand,Car Model,Car Color,Year of Manufacture,Credit Card Type
5560,Willard,Beard,Poland,Ford,Expedition EL,Purple,2009,laser
7131,Morgan,Shinefield,Philippines,Chevrolet,TrailBlazer,Red,2003,jcb
16641,Brewster,Bonicelli,Indonesia,Chevrolet,Cavalier,Puce,2004,jcb
25540,Annetta,Fairburne,Egypt,Toyota,TundraMax,Teal,2009,americanexpress
3182,Merrill,Opdenort,United States,Buick,LeSabre,Yellow,1999,diners-club-carte-blanche

In [4]:
# GET NUM OF COLOMS AND ROWS
print(f"Number of column :{car.shape[1]}\nNumber of rows :{car.shape[0]}")

Number of column :8
Number of rows :30000

In [5]:
# GET THE SUM OF NULL VALUES
car.isnull().sum()

First Name             0
Last Name              0
Country                0
Car Brand              0
Car Model              0
Car Color              0
Year of Manufacture    0
Credit Card Type       0
dtype: int64

In [6]:
# GET THE INFO 
car.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 8 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   First Name           30000 non-null  object
 1   Last Name            30000 non-null  object
 2   Country              30000 non-null  object
 3   Car Brand            30000 non-null  object
 4   Car Model            30000 non-null  object
 5   Car Color            30000 non-null  object
 6   Year of Manufacture  30000 non-null  int64
 7   Credit Card Type     30000 non-null  object
dtypes: int64(1), object(7)
memory usage: 1.8+ MB

In [7]:
pd.DataFrame({'count': car.shape[0],  
              'cardinality': car.nunique()
             })

                     count  cardinality
First Name           30000         8173
Last Name            30000        22192
Country              30000          230
Car Brand            30000           78
Car Model            30000         1006
Car Color            30000           19
Year of Manufacture  30000           65
Credit Card Type     30000           16

In [8]:
car.describe(exclude=np.number)

,First Name,Last Name,Country,Car Brand,Car Model,Car Color,Credit Card Type
count,30000,30000,30000,30000,30000,30000,30000
unique,8173,22192,230,78,1006,19,16
top,Tally,Carillo,China,Ford,Corvette,Indigo,jcb
freq,15,6,5465,2562,209,1627,12718

<div style="background-color: #4b3832; padding: 20px; border-radius: 10px; box-shadow: 5px 5px 10px #888888;">
  <h1 style="color: white; font-size: 30px; font-weight: bold; text-align: center; text-shadow: 2px 2px 4px #000000;">First Name 🧑</h1>
</div>

In [9]:
top_20_first_name_repeat = car['First Name'].value_counts()[0:20]

In [10]:
iplot(px.bar(top_20_first_name_repeat,
             title = 'top 20 first name repeated',
             color_discrete_sequence = colors,
             text_auto = True,
             labels = dict(index = 'First Name',value = 'sum')))

<div style="background-color: #4b3832; padding: 20px; border-radius: 10px; box-shadow: 5px 5px 10px #888888;">
  <h1 style="color: white; font-size: 30px; font-weight: bold; text-align: center; text-shadow: 2px 2px 4px #000000;">Last Name 👴</h1>
</div>

In [11]:
top_20_Last_name_repeat = car['Last Name'].value_counts()[0:20]

In [12]:
iplot(px.bar(top_20_Last_name_repeat,
             title = 'top 20 last name repeated',
             color_discrete_sequence = [colors[1]],
             text_auto = True,
             labels = dict(index = 'Last Name',value = 'sum')))

<div style="background-color: #4b3832; padding: 20px; border-radius: 10px; box-shadow: 5px 5px 10px #888888;">
  <h1 style="color: white; font-size: 30px; font-weight: bold; text-align: center; text-shadow: 2px 2px 4px #000000;">Country 🗺️</h1>
</div>

In [13]:
country_counts = car['Country'].value_counts().reset_index()
country_counts.columns = ['Country', 'count']

In [14]:
# Plotting the world map based on country occurrences
fig = px.choropleth(locations=country_counts['Country'], locationmode='country names', 
                    color=country_counts['count'], hover_name=country_counts['Country'],
                    title='Occurrences by Country')

fig.update_layout(geo=dict(bgcolor='black'))

fig.show()

In [15]:
top_10_country_counts = car['Country'].value_counts()[0:10]

In [16]:
iplot(px.bar(top_10_country_counts,
             title = 'top 10 country counts',
             color_discrete_sequence = [colors[3]],
             text_auto = True,
             labels = dict(index = 'Country',value = 'sum')))

<div style="background-color: #4b3832; padding: 20px; border-radius: 10px; box-shadow: 5px 5px 10px #888888;">
  <h1 style="color: white; font-size: 30px; font-weight: bold; text-align: center; text-shadow: 2px 2px 4px #000000;">Car Brand 🚘</h1>
</div>

In [17]:
top_15_car_brands = car['Car Brand'].value_counts().head(15).reset_index()
top_15_car_brands.columns = ['Car Brand', 'Count']

fig = px.scatter(top_15_car_brands,
                 x='Count',
                 y='Car Brand',
                 color='Car Brand',
                 color_discrete_sequence=[colors[4]],
                 size='Count',
                 labels={'Car Brand': 'Car Brand', 'Count': 'Count'},
                 title='Top 15 Car Brand')

fig.update_traces(marker=dict(symbol='circle', line=dict(width=0.5, color='DarkSlateGrey')),
                  selector=dict(mode='markers'))

fig.show()

<div style="background-color: #4b3832; padding: 20px; border-radius: 10px; box-shadow: 5px 5px 10px #888888;">
  <h1 style="color: white; font-size: 30px; font-weight: bold; text-align: center; text-shadow: 2px 2px 4px #000000;">Car Model 🚗</h1>
</div>

In [18]:
top_15_car_model = car['Car Model'].value_counts()[0:15]

In [19]:
iplot(px.bar(top_15_car_model,
             title = 'top 10 Car Model',
             color_discrete_sequence = [colors[5]],
             text_auto = True,
             labels = dict(index = 'Car Model',value = 'sum')))

<div style="background-color: #4b3832; padding: 20px; border-radius: 10px; box-shadow: 5px 5px 10px #888888;">
  <h1 style="color: white; font-size: 30px; font-weight: bold; text-align: center; text-shadow: 2px 2px 4px #000000;">Car Color </h1>
</div>

In [20]:
sum_car_colors = car['Car Color'].value_counts()

In [21]:
fig = px.line(x=sum_car_colors.index, y=sum_car_colors.values, markers=True, title='Counts of Car Colors')
fig.update_xaxes(title='Car Colors')
fig.update_yaxes(title='Count')
fig.show()

<div style="background-color: #4b3832; padding: 20px; border-radius: 10px; box-shadow: 5px 5px 10px #888888;">
  <h1 style="color: white; font-size: 30px; font-weight: bold; text-align: center; text-shadow: 2px 2px 4px #000000;">Year of Manufacture 📆</h1>
</div>

In [22]:
Year_of_Manufacture = car['Year of Manufacture'].value_counts()

In [23]:
fig = px.line(x=Year_of_Manufacture.index, y=Year_of_Manufacture.values, markers=True, title='Counts of Cars Manufactured by Year')
fig.update_xaxes(title='Year of Manufacture', type='category')  
fig.update_yaxes(title='Count')  
fig.update_traces(textposition='top right')  
fig.show()

In [24]:
fig = px.histogram(car, x='Year of Manufacture', 
                   title='Year of Manufacture Distribution in Top Hits', 
                   color_discrete_sequence=[colors[7]])  

fig.show()

<div style="background-color: #4b3832; padding: 20px; border-radius: 10px; box-shadow: 5px 5px 10px #888888;">
  <h1 style="color: white; font-size: 30px; font-weight: bold; text-align: center; text-shadow: 2px 2px 4px #000000;">Credit Card Type 💳</h1>
</div>

In [25]:
top_10_credit_card = car['Credit Card Type'].value_counts()

In [26]:
fig = px.pie(names=top_10_credit_card.index,
             values=top_10_credit_card.values,
             title="Top 10 Credit Card Distribution",
             color_discrete_sequence = colors)

fig.update_traces(textinfo='label+percent')
fig.show()

<div style="background-color: #4b3832; padding: 20px; border-radius: 10px; box-shadow: 5px 5px 10px #888888;">
  <h1 style="color: white; font-size: 30px; font-weight: bold; text-align: center; text-shadow: 2px 2px 4px #000000;">Thanks for visiting 🤩</h1>
</div>