In [5]:
import pandas as pd
import numpy as np

In [6]:
df = pd.read_csv('../../spreadsheets/iris.csv')
df.iloc[0,1] = pd.NA ; df.iloc[0,2] = pd.NA
df.iloc[1, 2] = np.nan ; df.iloc[2, 3] = None

df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          NaN           NaN          0.2  setosa
1           4.9          3.0           NaN          0.2  setosa
2           4.7          3.2           1.3          NaN  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [10]:
df.isnull().sum()
df.isnull().sum(axis=1)
df.loc[df.isnull().sum(axis=1)>0,:]

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          NaN           NaN          0.2  setosa
1           4.9          3.0           NaN          0.2  setosa
2           4.7          3.2           1.3          NaN  setosa

In [11]:
df = df.dropna()
df = df.reset_index(drop=True)
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           4.6          3.1           1.5          0.2  setosa
1           5.0          3.6           1.4          0.2  setosa
2           5.4          3.9           1.7          0.4  setosa
3           4.6          3.4           1.4          0.3  setosa
4           5.0          3.4           1.5          0.2  setosa