In [11]:
import pandas as pd
from sklearn.impute import KNNImputer

In [12]:
df_org = pd.read_csv('../../spreadsheets/iris.csv')
df_miss = df_org.copy()

In [13]:
df_miss.iloc[0,3] = pd.NA ; df_miss.iloc[0,2] = pd.NA
df_miss.iloc[1,2] = None ; df_miss.iloc[2,3] = None
df_miss.head(4)

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           NaN          NaN  setosa
1           4.9          3.0           NaN          0.2  setosa
2           4.7          3.2           1.3          NaN  setosa
3           4.6          3.1           1.5          0.2  setosa

In [14]:
tmp_np = df_miss.iloc[:, :4].to_numpy()
imputer = KNNImputer(n_neighbors=5)
tmp_np = imputer.fit_transform(tmp_np)
df_miss.iloc[:,:4] = tmp_np

In [15]:
df_miss.head(4)

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5          1.46         0.32  setosa
1           4.9          3.0          1.50         0.20  setosa
2           4.7          3.2          1.30         0.22  setosa
3           4.6          3.1          1.50         0.20  setosa

In [16]:
df_org.head(4)

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa