In [1]:
import pandas as pd
import itertools

In [2]:
df = pd.read_csv('../../spreadsheets/iris.csv')

In [3]:
df20 = df.sample(n=20, random_state =123)
df20

     sepal_length  sepal_width  petal_length  petal_width     species
72            6.3          2.5           4.9          1.5  versicolor
112           6.8          3.0           5.5          2.1   virginica
132           6.4          2.8           5.6          2.2   virginica
88            5.6          3.0           4.1          1.3  versicolor
37            4.9          3.1           1.5          0.1      setosa
138           6.0          3.0           4.8          1.8   virginica
87            6.3          2.3           4.4          1.3  versicolor
42            4.4          3.2           1.3          0.2      setosa
8             4.4          2.9           1.4          0.2      setosa
90            5.5          2.6           4.4          1.2  versicolor
141           6.9          3.1           5.1          2.3   virginica
33            5.5          4.2           1.4          0.2      setosa
59            5.2          2.7           3.9          1.4  versicolor
116           6.5          3.0           5.5          1.8   virginica
135           7.7          3.0           6.1          2.3   virginica
104           6.5          3.0           5.8          2.2   virginica
36            5.5          3.5           1.3          0.2      setosa
13            4.3          3.0           1.1          0.1      setosa
63            6.1          2.9           4.7          1.4  versicolor
45            4.8          3.0           1.4          0.3      setosa

In [4]:
stratified = df.groupby('species').apply(
                        lambda x: x.sample(frac=0.2, random_state =123))
stratified

                sepal_length  sepal_width  petal_length  petal_width
species
setosa     10            5.4          3.7           1.5          0.2
           13            4.3          3.0           1.1          0.1
           30            4.8          3.1           1.6          0.2
           46            5.1          3.8           1.6          0.2
           18            5.7          3.8           1.7          0.3
           0             5.1          3.5           1.4          0.2
           40            5.0          3.5           1.3          0.3
           12            4.8          3.0           1.4          0.1
           29            4.7          3.2           1.6          0.2
           8             4.4          2.9           1.4          0.2
versicolor 60            5.0          2.0           3.5          1.0
           63            6.1          2.9           4.7          1.4
           80            5.5          2.4           3.8          1.1
           96            5.7          2.9           4.2          1.3
           68            6.2          2.2           4.5          1.5
           50            7.0          3.2           4.7          1.4
           90            5.5          2.6           4.4          1.2
           62            6.0          2.2           4.0          1.0
           79            5.7          2.6           3.5          1.0
           58            6.6          2.9           4.6          1.3
virginica  110           6.5          3.2           5.1          2.0
           113           5.7          2.5           5.0          2.0
           130           7.4          2.8           6.1          1.9
           146           6.3          2.5           5.0          1.9
           118           7.7          2.6           6.9          2.3
           100           6.3          3.3           6.0          2.5
           140           6.7          3.1           5.6          2.4
           112           6.8          3.0           5.5          2.1
           129           7.2          3.0           5.8          1.6
           108           6.7          2.5           5.8          1.8

In [6]:
species = df.species.unique()
comb = list(itertools.combinations(species, 2))
comb

[('setosa', 'versicolor'),
 ('setosa', 'virginica'),
 ('versicolor', 'virginica')]