In [8]:
import pandas as pd

In [9]:
df = pd.read_csv ('../../spreadsheets/iris.csv')

In [10]:
df_sorted = df.sort_values('sepal_length')
df_sorted.head(10)

    sepal_length  sepal_width  petal_length  petal_width species
13           4.3          3.0           1.1          0.1  setosa
8            4.4          2.9           1.4          0.2  setosa
42           4.4          3.2           1.3          0.2  setosa
38           4.4          3.0           1.3          0.2  setosa
41           4.5          2.3           1.3          0.3  setosa
22           4.6          3.6           1.0          0.2  setosa
3            4.6          3.1           1.5          0.2  setosa
6            4.6          3.4           1.4          0.3  setosa
47           4.6          3.2           1.4          0.2  setosa
2            4.7          3.2           1.3          0.2  setosa

In [11]:
df_sorted = df.sort_values('sepal_length', ascending=False)
df_sorted.head(10)

     sepal_length  sepal_width  petal_length  petal_width    species
131           7.9          3.8           6.4          2.0  virginica
122           7.7          2.8           6.7          2.0  virginica
118           7.7          2.6           6.9          2.3  virginica
117           7.7          3.8           6.7          2.2  virginica
135           7.7          3.0           6.1          2.3  virginica
105           7.6          3.0           6.6          2.1  virginica
130           7.4          2.8           6.1          1.9  virginica
107           7.3          2.9           6.3          1.8  virginica
109           7.2          3.6           6.1          2.5  virginica
129           7.2          3.0           5.8          1.6  virginica

In [12]:
df_sorted = df.sort_values(['species','sepal_width'])
df_sorted.head (10)

    sepal_length  sepal_width  petal_length  petal_width species
41           4.5          2.3           1.3          0.3  setosa
8            4.4          2.9           1.4          0.2  setosa
1            4.9          3.0           1.4          0.2  setosa
12           4.8          3.0           1.4          0.1  setosa
13           4.3          3.0           1.1          0.1  setosa
25           5.0          3.0           1.6          0.2  setosa
38           4.4          3.0           1.3          0.2  setosa
45           4.8          3.0           1.4          0.3  setosa
3            4.6          3.1           1.5          0.2  setosa
9            4.9          3.1           1.5          0.1  setosa

In [15]:
# Ranking ni sya part
df['petal_length'].rank().astype(int) # Ascending rank

0       17
1       17
2        8
3       30
4       17
      ...
145    117
146    106
147    117
148    121
149    112
Name: petal_length, Length: 150, dtype: int64

In [14]:
df['petal_length'].rank(ascending = False).astype(int) # Descending rank

0      133
1      133
2      143
3      120
4      133
      ...
145     33
146     44
147     33
148     29
149     38
Name: petal_length, Length: 150, dtype: int64